import numpy as np
import matplotlib.pyplot as plt


def plot_verlet_times():
    """Plot times generated by run_verlet_times."""
    data = np.genfromtxt("verlet_times.txt")
    rv, real, user, sys = data.T
    plt.title("Verlet list radius vs. total CPU time")
    plt.xlabel(r"Verlet Radius ($\sigma$)")
    plt.ylabel("CPU time (s)")
    plt.plot(rv, real + sys)
    plt.grid()
    plt.savefig("verlet_times", dpi=600)
