#!/usr/bin/env bash

f="verlet_times.txt"
printf "# rv \treal\tuser\tsys\n" > "$f"

rmin=$(python -c 'print 2 ** (1/6.)')
rv2=$(python -c 'print 1.05 * 2 ** (1/6.)')
temp=0.728

for rv in $(seq 2.5 0.001 3.5) ; do
  cat > fort.15  <<endofdata
  ibeg  , delt  tmax  tequil nsamp
   0     0.001  1.5   0.00  1
npart temp 	rho  	iseed
500   ${temp} 	0.8442	123456
 scale  temp
 .true.  0.728
iout igr     iout2  ivacf	t0vacf      t0stress iout3    iout4
33   10      34     10000000      100       100000        35   36
samp1    samp2   tdifmax
.true.  .false.   100
rcp	rv	rc2      rv2
2.5     ${rv}	${rmin}    ${rv2}
multi	n
.false.	1
endofdata
  cp lj.res          fort.11

  # time the run
  printf "%s\t" "$rv" >> "$f"
  /usr/bin/time -f "%e\t%U\t%S" -o "$f" -a ../Source/MD

  cp fort.21         lj.res
  mv fort.66         lj.prt
  mv fort.33         lj.gr
  #perform block analysis
  cp lj.prth fort.31
  mv  lj.prt fort.32
  # ../Block/block
  rm fort.*
done
